spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5433/user_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
  
  cloud:
    openfeign:
        client:
            config:
                default:
                    connect-timeout: 5000
                    read-timeout: 5000

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/